FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

FROM alpine:3.20

WORKDIR /root/
COPY --from=builder /app/app ./app

EXPOSE 8080

CMD ["./app"]
