services:
  db:
    image: mysql:8.0
    container_name: bai8_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    build: .
    container_name: bai8_node_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_PORT: 3306
